here/here/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

# https://docs.djangoproject.com/en/3.1/ref/urls/#handler403
from django.conf.urls import handler400, handler403, handler404, handler500
from pages import views as page_views
from members import views as member_views
from poems import views as poem_views

urlpatterns = [
    path("", page_views.index, name="index"),
    path('sitemap.xml', page_views.sitemap, name="sitemap"),
    path('sitemaps.xml', page_views.sitemap),
    path('admin/', admin.site.urls),
    re_path(r'^profile-.*-(?P<user_id>\d+)\.html$', member_views.profile, name="member_profile"),
    re_path(r'^profile-(?P<user_id>\d+)\.html$', member_views.profile, name="member_profile_id"),
   	path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
    path('login.html',auth_views.LoginView.as_view(template_name='members/login.html'), name='login'),
    path('logout.html', auth_views.LogoutView.as_view(template_name="members/logged_out.html"), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name="accounts/password_change_form.html"), name="password_change"),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"), name="password_change_done"),
    path('members/', include('members.urls')),
    # path('search.html', poem_views.search_get, name="poem_search_get"),
    path('rss2.xml', page_views.rss2, name="rss2"),
    path('robots.txt', page_views.robots, name="robots"),
    # path('search_advanced.html', poem_views.search_advanced, name="search_advanced"),
    path("register-eft.html", member_views.register_eft, name="register_eft"),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset_form.html", from_email=settings.EMAIL_FROM), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"), name='password_reset_done'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), name='password_reset_complete'),
    re_path(r'^eft-(?P<sha512>\w+)\.json$', poem_views.eft_get, name="root_eft"),
    path('poems/', include('poems.urls')),
    path('search.html', poem_views.search_get, name="poem_search_get"),
    path('search_advanced.html', poem_views.search_advanced, name="search_advanced"),
]

handler400 = page_views.catch_redirect
handler403 = page_views.catch_redirect
handler404 = page_views.catch_redirect
handler500 = page_views.catch_redirect


# Sources:
# https://docs.djangoproject.com/en/3.1/topics/auth/default/

here/members/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'members'

urlpatterns = [
    path('list.html', views.list, name='list'),
    path('welcome.html', views.welcome, name='welcome'),
    path('edit.html', views.edit, name='edit'),
    path('edit_update.html', views.edit_update, name='edit_update'),
    path('add_book.html', views.add_book, name='add_book'),
    path('book/<int:book_id>/delete.html', views.delete_book, name="delete_book"),
]

# Sources:
# https://docs.djangoproject.com/en/3.1/topics/http/urls/

here/members/models.py
from django.db import models
from simple_history.models import HistoricalRecords
from django.contrib.auth.models import User
from django.conf import settings
from django_resized import ResizedImageField
from .templatetags import member_tag_extras
from pages.models import Rss2
import uuid
import subprocess
import hashlib

class Member(models.Model):
    pricing = models.CharField(max_length=255, choices=settings.PRICING_CHOICES, default=settings.MEMBER_PRICING_FREE)
    user = models.ForeignKey(User, related_name="member_user", null=True, blank=True, on_delete=models.CASCADE)
    history = HistoricalRecords()
    standing = models.CharField(max_length=255, choices=settings.STANDING_CHOICES, default=settings.MEMBER_STANDING_PAID)
    ux_poem_item_search = models.CharField(max_length=255, choices=settings.POEM_ITEM_SEARCH_CHOICES, default=settings.POEM_ITEM_SEARCH_DEFAULT_CHOICE)
    ux_home_screen = models.CharField(max_length=255, choices=settings.HOME_SCREEN_CHOICES, default=settings.HOME_SCREEN_DEFAULT_CHOICE)
    ux_show_diff_on_poem_items = models.CharField(max_length=255, choices=settings.SHOW_DIFF_ON_POEM_ITEMS_CHOICES, default=settings.SHOW_DIFF_ON_POEM_ITEMS_DEFAULT_CHOICE)
    bio = models.TextField(null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    source = models.CharField(max_length=255, null=True, blank=True)
    referral = models.CharField(max_length=255, null=True, blank=True)
    ux_sell_all_poems_as_eft = models.CharField(max_length=255, choices=settings.SELL_ALL_POEMS_AS_EFT_CHOICES, default=settings.SELL_ALL_POEMS_AS_EFT_DEFAULT_CHOICE)
    guid = models.UUIDField(primary_key=False, default=uuid.uuid4, editable=False)
    ux_tips = models.CharField(max_length=255, choices=settings.TIPS_CHOICES, default=settings.TIPS_DEFAULT_CHOICE)
    transfer_key_type = models.CharField(max_length=255, choices=settings.TRANSFER_KEY_TYPE_CHOICES, default=settings.TRANSFER_KEY_TYPE_DEFAULT_CHOICE)
    contract_address = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):  
        return self.user.username + ": " + self.pricing + " as " + self.standing


    def save(self, *args, **kwargs):
        if self.guid and not self.contract_address:
            self.contract_address = self.get_contract_address(skip_save=True)

        return super(Member, self).save(*args, **kwargs)

    def get_contract_address(self, skip_save=False):
        if self.contract_address:
            return self.contract_address

        # offer_contract_address = str(hex(offer_guid_as_int))
        cmd = 'osprey_app_divide_me-inlovelike-v1 1 ' + settings.HTTPS_BASE_URL
        diff = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, executable="/bin/bash")
        diff_return = str(diff.stdout.read())
        diff.terminate()

        host_sha_hexdigest = hashlib.sha512(diff_return.encode('utf-8')).hexdigest()
                
        address_text = host_sha_hexdigest + ' Member GUID: ' + str(self.guid)
        address_digest = hashlib.sha512(address_text.encode('utf-8')).digest()
        address_digest_as_int = int.from_bytes(address_digest, 'big')
        
        address = str(hex(address_digest_as_int))

        self.contract_address = address

        if not skip_save:
            self.save()

        return address


class Book(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    user = models.ForeignKey(User, related_name="book_user", on_delete=models.CASCADE)
    image = ResizedImageField(size=[286, 180], upload_to='members/books', blank=False)

    history = HistoricalRecords()


    def save(self, *args, **kwargs):
        rss = {
            'title': self.title,
            'url': member_tag_extras.author_url(self.user)
        }
        if self.id:
            rss['description'] = "Updated book on profile"
        else:
            rss['description'] = "Created a new book for a profile"
        
        try:
            Rss2.objects.create(title=rss['title'],description=rss['description'],url=rss['url'])
        except Exception as e:
            print("Failed to create RSS2 object")
            print(rss)
            print(e)

        return super(Book, self).save(*args, **kwargs)


# Sources:
# https://stackoverflow.com/questions/31130706/dropdown-in-django-model

here/members/forms.py
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from captcha.fields import ReCaptchaField
from django.conf import settings
from django.template.defaultfilters import filesizeformat
from members.models import Book
# from poems.models import Poem

class MemberPoemForm(forms.Form):
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	password =  forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

	poem_title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Enter title of Poem", 'class': 'form-control'}))
	poem_body = forms.CharField(
		initial='', 
		widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
	)

	if settings.FEATURE_CAPTCHA:
		captcha = ReCaptchaField()

	fields = ['username', 'first_name', 'last_name', 'email', 'password', 'password_confirmation', 'poem_title', 'poem_body']

	def clean_username(self):
		data = self.cleaned_data['username']

		try:
			user = User.objects.get(username=data)
		except:
			user = False

		if user:
			raise ValidationError(
				_('%(username)s has already been taken. Please try another.'),
				params={'username': data},
			)

		# Always return a value to use as the new cleaned data, even if
		# this method didn't change it.
		return data

	def clean_email(self):
		data = self.cleaned_data['email']

		try:
			user = User.objects.get(email=data)
		except:
			user = False

		if user:
			raise ValidationError(
				_('%(email)s already in use. Please login with this.'),
				params={'email': data},
			)

		# Always return a value to use as the new cleaned data, even if
		# this method didn't change it.
		return data


class MemberProfessionalForm(forms.Form):
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	password =  forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	if settings.FEATURE_CAPTCHA:
		captcha = ReCaptchaField()

	fields = ['first_name', 'last_name', 'username', 'password', 'email']

	def clean_username(self):
		data = self.cleaned_data['username']

		try:
			user = User.objects.get(username=data)
		except:
			user = False

		if user:
			raise ValidationError(
				_('%(username)s has already been taken. Please try another.'),
				params={'username': data},
			)

		# Always return a value to use as the new cleaned data, even if
		# this method didn't change it.
		return data

	def clean_email(self):
		data = self.cleaned_data['email']

		try:
			user = User.objects.get(email=data)
		except:
			user = False

		if user:
			raise ValidationError(
				_('%(email)s already in use. Please login with this.'),
				params={'email': data},
			)

		# Always return a value to use as the new cleaned data, even if
		# this method didn't change it.
		return data


class MemberProfileForm(forms.Form):
	ux_poem_item_search = forms.ChoiceField(label='Display of Poem Search Icons by Default', widget=forms.Select(attrs={'class': 'form-control'}), choices=settings.POEM_ITEM_SEARCH_CHOICES)
	ux_home_screen = forms.ChoiceField(label='Home Screen', widget=forms.Select(attrs={'class': 'form-control'}), choices=settings.HOME_SCREEN_CHOICES)
	ux_tips = forms.ChoiceField(label="Amount of Alert TIP's within the User Interface", widget=forms.Select(attrs={'class': 'form-control'}), choices=settings.TIPS_CHOICES)

	fields = ['ux_poem_item_search', 'ux_home_screen']


class MemberProfessionalProfileForm(forms.Form):
	bio = forms.CharField(
		required=False,
		initial='', 
		widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
	)
	website = forms.URLField(required=False, widget=forms.URLInput(attrs={'class': 'form-control'}))

	ux_show_diff_on_poem_items = forms.ChoiceField(label='Display changes on pieces of Poetry within the item details page', widget=forms.Select(attrs={'class': 'form-control'}), choices=settings.SHOW_DIFF_ON_POEM_ITEMS_CHOICES)

	ux_sell_all_poems_as_eft = forms.ChoiceField(label="Do you want to sell all your poems as EFT's and selectively exclude the ones you don't want to sell?", widget=forms.Select(attrs={'class': 'form-control'}), choices=settings.SELL_ALL_POEMS_AS_EFT_CHOICES)

	fields = ['bio', 'website', 'ux_show_diff_on_poem_items', 'ux_sell_all_poems_as_eft']


class BookForm(ModelForm):
	class Meta:
		model = Book
		fields = ['title', 'url', 'image']

		labels = {
			"title": "Title of book",
            "url": "Website address to acquire book",
            "image": "Cover image of book",
        }

		widgets = {
			'title': forms.TextInput(attrs={'placeholder': "Your title here", 'class': 'form-control'}),
			'url': forms.URLInput(attrs={'placeholder': "https://", 'class': 'form-control'}),
			'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
		}

	# Verify content type is an image
	# UploadedFile.content_type
	def clean_image(self):
	    i = self.cleaned_data['image']
	    content_type = i.content_type.split('/')[0]
	    if content_type in settings.BOOK_IMAGE_TYPES:
	        if int(i.size) > int(settings.BOOK_IMAGE_MAX_UPLOAD_SIZE):
	            raise forms.ValidationError(_('Please keep filesize under %s. Current filesize %s') % (filesizeformat(settings.MAX_UPLOAD_SIZE), filesizeformat(content._size)))
	    else:
	        raise forms.ValidationError(_('File type is not supported'))
	    return i


class MemberBasicForm(forms.Form):
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	password =  forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	if settings.FEATURE_CAPTCHA:
		captcha = ReCaptchaField()

	fields = ['first_name', 'last_name', 'username', 'password', 'email']

	def clean_username(self):
		data = self.cleaned_data['username']

		try:
			user = User.objects.get(username=data)
		except:
			user = False

		if user:
			raise ValidationError(
				_('%(username)s has already been taken. Please try another.'),
				params={'username': data},
			)

		# Always return a value to use as the new cleaned data, even if
		# this method didn't change it.
		return data

	def clean_email(self):
		data = self.cleaned_data['email']

		try:
			user = User.objects.get(email=data)
		except:
			user = False

		if user:
			raise ValidationError(
				_('%(email)s already in use. Please login with this.'),
				params={'email': data},
			)

		# Always return a value to use as the new cleaned data, even if
		# this method didn't change it.
		return data

class UserForm(forms.Form):
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

	fields = ['username', 'first_name', 'last_name', 'email']


# Sources: 
# https://docs.djangoproject.com/en/3.1/topics/forms/modelforms/
# https://docs.djangoproject.com/en/3.1/ref/forms/api/
# https://docs.djangoproject.com/en/3.1/ref/forms/fields/
# https://docs.djangoproject.com/en/3.1/ref/models/fields/
# https://docs.djangoproject.com/en/3.1/ref/forms/validation/
# https://stackoverflow.com/questions/48030567/how-to-customize-username-validation
# https://stackoverflow.com/questions/9324432/how-to-create-password-input-field-in-django
# https://docs.djangoproject.com/en/3.1/ref/validators/
# https://docs.djangoproject.com/en/3.1/ref/forms/api/
# https://docs.djangoproject.com/en/3.1/ref/forms/validation/
# https://docs.djangoproject.com/en/3.1/ref/forms/api/
# https://stackoverflow.com/questions/4788388/how-do-i-use-djangos-form-framework-for-select-options
# https://docs.djangoproject.com/en/3.1/topics/http/file-uploads/
# https://docs.djangoproject.com/en/3.1/ref/files/uploads/
# https://www.djangosnippets.org/snippets/1303/
# https://stackoverflow.com/questions/20986798/django-modelform-label-customization
# https://docs.djangoproject.com/en/3.1/ref/forms/fields/

here/members/templates/members/add_book.html
{% extends "theme.html" %}
{% load member_tag_extras %}
{% block content %}
<h4>Add Book to Profile</h4>
<p>By adding a book to reference your poetry, viewers will be able to find more of your work by simply following the link of the cover image to acquire the book.</p>

<form action="{% url 'members:add_book' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <div>
		<button type="submit" class="btn btn-lg btn-success mt-4">Save</button>
	</div>
</form>

{% endblock %}
{% comment %}
Sources: 
https://getbootstrap.com/docs/4.0/components/forms/
https://docs.djangoproject.com/en/3.1/topics/forms/
https://getbootstrap.com/docs/4.0/utilities/text/
https://stackoverflow.com/questions/14268342/make-the-first-letter-uppercase-inside-a-django-template
{% endcomment %}

here/members/templates/members/edit.html
{% extends "theme.html" %}
{% load member_tag_extras %}
{% block content %}
<h4>Edit Profile Settings</h4>

	{% if success %}
<div class="alert alert-success" role="alert">
	That was a success.
</div>
	{% endif %}
	{% if error %}
<div class="alert alert-warning" role="alert">
	There was an error. Please try again!
</div>
	{% endif %}


<a class="btn btn-sm btn-secondary" href="{{ request.user|author_url }}" title="Poet Member Profile">View Profile</a>
<p>Here you will find more details about your membership profile such as settings in the system:</p>

	{% if request.user|member_tips_is:'some' or request.user|member_tips_is:'verbose' %}
	<div class="alert alert-info alert-dismissible fade show" role="alert">
		<strong>Settings</strong> for your membership plan including changing things like what your homescreen is as well as whether the search functionality is displayed automatically by default within the details of each Poem. In addition for Professional Poets, you may modify your bio, website, and make global content changes for your profile by specifying whether you would like to sell Poems as EFT's. In addition, you may also specify whether you want to display changes for made to your Poems. 
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
		</button>
	</div>
	{% endif %}

<p>
	<span class="font-weight-bold">Pricing:</span> {{ request.user|member_pricing|title }}
</p>
<p><span class="font-weight-bold">Membership Standing:</span> {{ request.user|member_standing|title }}</p>

<form action="{% url 'members:edit_update' %}" method="post">
    {% csrf_token %}
    {{ user_form }}
	<button type="submit" class="btn btn-lg btn-success mt-4">Save</button>
</form>

<form action="{% url 'members:edit' %}" method="post" class="mt-3">
    {% csrf_token %}
    {{ form }}
	<button type="submit" class="btn btn-lg btn-success mt-4">Save</button>
</form>

{% if form_member_professional_profile is not False %}
<h6 class="mt-3">Professional Settings</h6>
<form action="{% url 'members:edit' %}" method="post">
    {% csrf_token %}
    {{ form_member_professional_profile }}
	<button type="submit" class="btn btn-lg btn-success mt-4">Save</button>
</form>
{% endif %}


{% if books %}
{% if books|length > 1 %}<h6 class="mt-3">Books</h6>{% endif %}
<div class="card-columns books mb-3 mt-3">
	{% for book in books %}
	<div class="card">
		<img class="card-img-top" src="{{ book.image.url }}" alt="{{ book.title }}">
		<div class="card-body">
		    <h5 class="card-title">{{book.title}}</h5>
	        <p class="card-text">{{ book.url }}</p>
		    <a href="/members/book/{{book.id}}/delete.html" class="btn btn-sm btn-warning"><i class="fas fa-trash-alt"></i> Delete</a>
		</div>
	</div>
	{% endfor %}
</div>
	{% if request.user|member_is_pro or request.user|member_is_unlimited %}
<a href="{% url 'members:add_book' %}" class="btn btn-sm btn-primary"><i class="fas fa-book"></i> Add Book</a>
	{% endif %}
{% else %}
<p class="mt-3"><a href="{% url 'members:add_book' %}" class="btn btn-sm btn-primary"><i class="fas fa-book"></i> Add Book</a></p>
{% endif %}


{% endblock %}
{% comment %}
Sources: 
https://getbootstrap.com/docs/4.0/components/forms/
https://docs.djangoproject.com/en/3.1/topics/forms/
https://getbootstrap.com/docs/4.0/utilities/text/
https://stackoverflow.com/questions/14268342/make-the-first-letter-uppercase-inside-a-django-template
{% endcomment %}

here/members/templates/members/list.html
{% extends "theme.html" %}
{% load member_tag_extras %}
{% block content %}
<h4>Membership List</h4>
<p class="text-info">Here are the totals for inLoveLike membership:</p>
<p>Total Staff: {{ staff|length }}</p>
	<div class="card-columns staff mb-3">
		{% for user in staff %}
		<div class="card">
			<div class="card-body">
			    <h5 class="card-title"><a href="{{ user|author_url }}" rel="external"><i class="fas fa-users-cog"></i> <i class="fa fa-copyright" aria-hidden="true"></i> {{ user|author_title }}</a></h5>
			</div>
		</div>
		{% endfor %}
	</div>
<p>Total Members: {{ members|length }}</p>
{% endblock %}

here/members/templates/members/logged_out.html
{% extends "theme.html" %}
{% load i18n %}

{% block content %}

<p>{% translate "Thanks for spending some quality time with inLoveLike today." %}</p>

<p><a href="{% url 'login' %}">{% translate 'Log in again' %}</a></p>

{% endblock %}

here/members/templates/members/login.html
{% extends "theme.html" %}

{% block title %}Login for Poets - inLoveLike - Poetry with Poems{% endblock %}
{% block seo_description %}Login for Poets into the site to maintain your very own Poetry{% endblock %}

{% block content %}

{% if form.errors %}
<p class="text-danger">Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p class="text-danger">Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p class="text-info">Please login to see this page.</p>
    {% endif %}
{% endif %}
<p class="text-dark">Here you will find a login page for inLoveLike. Please continue by entering your username and password. Once logged in, you will be able to manage your EFT Purchases</p>
<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

    <div class="g-recaptcha mt-3" data-sitekey="6LeheaIaAAAAAE1OtLK78emV-CFRWnLEbdX_gSsP"></div>

<input class="btn btn-lg btn-success mt-2" type="submit" value="Login">
<input type="hidden" name="next" value="{{ next }}">
</form>

 <div class="password-reset-link mt-3">
    <a href="{% url 'password_reset' %}">Forgotten your password? Reset your password here.</a>
  </div>


{% endblock %}

here/members/templates/members/password_change_form.html
{% extends "theme.html" %}
{% block content %}<div id="content-main">

<form method="post">{% csrf_token %}
<div>
{% if form.errors %}
    <p class="errornote">
    {% if form.errors.items|length == 1 %}{% translate "Please correct the error below." %}{% else %}{% translate "Please correct the errors below." %}{% endif %}
    </p>
{% endif %}


<p>{% translate 'Please enter your old password, for security’s sake, and then enter your new password twice so we can verify you typed it in correctly.' %}</p>

<fieldset class="module aligned wide">

<div class="form-row">
    {{ form.old_password.errors }}
    {{ form.old_password.label_tag }} {{ form.old_password }}
</div>

<div class="form-row">
    {{ form.new_password1.errors }}
    {{ form.new_password1.label_tag }} {{ form.new_password1 }}
    {% if form.new_password1.help_text %}
    <div class="help">{{ form.new_password1.help_text|safe }}</div>
    {% endif %}
</div>

<div class="form-row">
{{ form.new_password2.errors }}
    {{ form.new_password2.label_tag }} {{ form.new_password2 }}
    {% if form.new_password2.help_text %}
    <div class="help">{{ form.new_password2.help_text|safe }}</div>
    {% endif %}
</div>

</fieldset>

<div class="submit-row">
    <input type="submit" value="{% translate 'Change my password' %}" class="default">
</div>

</div>
</form></div>

{% endblock %}

here/members/templates/members/password_reset_form.html
{% extends "theme.html" %}

{% block content %}

<p>{% translate 'Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.' %}</p>

<form method="post">{% csrf_token %}
<fieldset class="module aligned">
    <div class="form-row field-email">
        {{ form.email.errors }}
        <label for="id_email">{% translate 'Email address:' %}</label>
        {{ form.email }}
    </div>
    <input type="submit" value="{% translate 'Reset my password' %}">
</fieldset>
</form>

{% endblock %}

here/members/templates/members/register-eft.html
{% extends "theme.html" %}
{% load poem_tag_extras %}
{% block content %}
<h4>EFT Housing and Reselling Registration</h4>
<p>Below you will find a simple form to create your account allowing you to import Electronic File Tokens (EFT) into the system and begin optionally reselling them at this server rate {{ False|eft_cost_per_byte|safe }}</p>
<p>inLoveLike does not charge for this membership, so please do enjoy your free account. Thank you!</p>

<form action="{% url 'register_eft' %}" method="post">
    {% csrf_token %}
    {{ form }}
	<div class="g-recaptcha mt-3" data-sitekey="6LeheaIaAAAAAE1OtLK78emV-CFRWnLEbdX_gSsP"></div>

	<button type="submit" class="btn btn-primary mt-4">Start housing any EFT and by choice resell them here!</button>
</form>

{% endblock %}
{% comment %}
Sources: 
https://getbootstrap.com/docs/4.0/components/forms/
https://docs.djangoproject.com/en/3.1/topics/forms/
{% endcomment %}