here/here/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

# https://docs.djangoproject.com/en/3.1/ref/urls/#handler403
from django.conf.urls import handler400, handler403, handler404, handler500
from pages import views as page_views
from members import views as member_views
from poems import views as poem_views

urlpatterns = [
    path("", page_views.index, name="index"),
    path('sitemap.xml', page_views.sitemap, name="sitemap"),
    path('sitemaps.xml', page_views.sitemap),
    path('admin/', admin.site.urls),
    re_path(r'^profile-.*-(?P<user_id>\d+)\.html$', member_views.profile, name="member_profile"),
    re_path(r'^profile-(?P<user_id>\d+)\.html$', member_views.profile, name="member_profile_id"),
   	path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
    path('login.html',auth_views.LoginView.as_view(template_name='members/login.html'), name='login'),
    path('logout.html', auth_views.LogoutView.as_view(template_name="members/logged_out.html"), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name="accounts/password_change_form.html"), name="password_change"),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"), name="password_change_done"),
    path('members/', include('members.urls')),
    # path('search.html', poem_views.search_get, name="poem_search_get"),
    path('rss2.xml', page_views.rss2, name="rss2"),
    path('robots.txt', page_views.robots, name="robots"),
    # path('search_advanced.html', poem_views.search_advanced, name="search_advanced"),
    path("register-eft.html", member_views.register_eft, name="register_eft"),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset_form.html", from_email=settings.EMAIL_FROM), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"), name='password_reset_done'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), name='password_reset_complete'),
    re_path(r'^eft-(?P<sha512>\w+)\.json$', poem_views.eft_get, name="root_eft"),
    path('poems/', include('poems.urls')),
    path('search.html', poem_views.search_get, name="poem_search_get"),
    path('search_advanced.html', poem_views.search_advanced, name="search_advanced"),
]

handler400 = page_views.catch_redirect
handler403 = page_views.catch_redirect
handler404 = page_views.catch_redirect
handler500 = page_views.catch_redirect


# Sources:
# https://docs.djangoproject.com/en/3.1/topics/auth/default/

here/members/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'members'

urlpatterns = [
    path('list.html', views.list, name='list'),
    path('welcome.html', views.welcome, name='welcome'),
    path('edit.html', views.edit, name='edit'),
    path('edit_update.html', views.edit_update, name='edit_update'),
    path('add_book.html', views.add_book, name='add_book'),
    path('book/<int:book_id>/delete.html', views.delete_book, name="delete_book"),
]

# Sources:
# https://docs.djangoproject.com/en/3.1/topics/http/urls/

here/poems/urls.py
# from django.urls import include, path, re_path

from . import views
from django.urls import path, re_path


app_name = 'poems'
urlpatterns = [
    path('eft_offers.html', views.eft_offers, name='eft_offers'),
    path('eft_purchases.html', views.eft_purchases, name='eft_purchases'),
    path('eft-purchase-gallery/<int:eft_purchase_id>/', views.eft_purchase_gallery, name='eft_purchase_gallery'),
    path('eft-purchase-remove/<int:eft_purchase_id>/', views.eft_purchase_remove, name='eft_purchase_remove'),
    path('eft-purchase-offer/<uuid:eft_purchase_guid>/', views.eft_purchase_offer, name='eft_purchase_offer'),
    re_path(r'^eft-purchase-offer-sold/(?P<guid>.*)/$', views.eft_purchase_offer_sold, name="eft_purchase_offer_sold"),
    re_path(r'^eft-purchase-offer-refund/(?P<guid>.*)/$', views.eft_purchase_offer_refund, name="eft_purchase_offer_refund"),
    path('eft-purchase-resell/<int:eft_purchase_id>/', views.eft_purchase_resell, name='eft_purchase_resell'),
    path('eft_purchase_upload_ajax', views.eft_purchase_upload_ajax, name='eft_purchase_upload_ajax'),
    re_path(r'^eft-transfer-get/(?P<sha512>.*).json$', views.eft_transfer_get, name="eft_transfer_get"),
]

here/templates/hello_world.html
{% load static %}
{% block content %}
	<ul>
		<li><a href="https://www.facebook.com/inlovelike/">Facebook</a></li>
		<li><a href="https://www.instagram.com/inlovelike_/">Instagram</a></li>
		<li><a href="https://twitter.com/inlovelike_">Twitter</a></li>
	</ul>
	<footer>
		<p>&copy; <a href="http://nshbrown.com/?inlovelike">Nathaniel Steven Henry Brown</a>. All Rights Reserved.</p>
	</footer>
{% load static %}

here/templates/sitemap.html
{% extends 'theme.html' %}
{% load member_tag_extras %}
{% load poem_tag_extras %}
{% block content %}
<h4>inLoveLike SiteMap</h4>
<h5>Current as of {{ now|date:'Y-m-d' }}</h5>
<ul>
	<li>
		<a href="{{ request|host }}">Home</a> 
		<small>{{ poems_last_modified|mod_min|date:'Y-m-d' }}</small>
	</li>
<li>
	<a href="{{ request|host_no_slash }}{% url 'members:list' %}">Members List</a>
	<small>{{ False|mod_min|date:'Y-m-d' }}</small>
</li>
<li>
	<a href="{{ request|host_no_slash }}{% url 'login' %}">Login</a>
	<small>{{ False|mod_min|date:'Y-m-d' }}</small>
</li>
<li>
	<a href="{{ request|host_no_slash }}{% url 'register_eft' %}">Register for Electronic File Tokens</a>
	<small>{{ False|mod_min|date:'Y-m-d' }}</small>
</li>
</ul>
{% endblock %}

here/templates/theme.html
{% load static %}
{% load poem_tag_extras %}
{% load page_tag_extras %}
{% load member_tag_extras %}
<!doctype html>
<html lang="en">
	<head>	    
		<title>{% block title %}{% if seo_title %}{{ seo_title }}{% else %}Here of inLoveLike - Poetry with Poems{% endif %}{% endblock %}</title>
		<meta name="description" content="{% block seo_description %}{% if seo_description %}{{ seo_description }}{% else %}Poetry with Poems. Pieces of poetry shared by authors with book references if available.{% endif %}{% endblock %}" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
	    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
	    <link rel="alternate" type="application/rss+xml" title="RSS Feed for inlovelike.com" href="{% url 'rss2' %}" />
		<link rel="stylesheet" href="{% static 'bootstrap-4.5.0.min.css' %}" />
		<link rel="stylesheet" href="{% static 'bootstrap-social.css' %}" />
		{% block extrastyle %}
		{% endblock %}
		<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
		<script src="{% static 'popperjs-v2.9.2.js' %}"></script>
		<script src="{% static 'bootstrap.bundle-4.5.0.min.js' %}"></script>
		<script src="https://kit.fontawesome.com/edefd16c15.js" crossorigin="anonymous"></script>
		<script src="{% static 'theme.js' %}"></script>
		<link rel="stylesheet" href="{% static 'theme.css' %}" />
		<script src="https://www.google.com/recaptcha/enterprise.js" async defer></script>
	</head>
	<body class="d-flex flex-column h-100">
		<main class="flex-shrink-0">
		  	<div class="container-md">
		  		<div class="title-slogan">
					<h1 class="title"><a href="{{ request.user|home_screen_url }}" title="Poetry with Poems"><img src="{% static 'thumbnail-v2_0-202103271109.png' %}" height="200" alt="Poetry with Poems" /> <span>inLoveLike</span></a></h1>
					<h2 class="d-none d-md-block">Here EFT Server</h2>
				</div>
<nav class="navbar navbar-expand-xl navbar-light bg-light mb-4">
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				    	<span class="navbar-toggler-icon"></span>
					</button>

					<div class="collapse navbar-collapse" id="navbarSupportedContent">
						<ul class="navbar-nav mr-auto">
							<li class="nav-item nav-logo">
								<a href="{{ request.user|home_screen_url }}">
									<img src="{% static 'favicon-v2_0-202103271109.png' %}" width="32" height="32" class="align-top" alt="inLoveLike - Poetry with Poems">
									<span>inLoveLike</span>
								</a>
							</li>
	{% if request.user.is_authenticated %}
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle {% if request|active_link_class:'/' or request|active_link_class:'/poems/my.html' %}active{% endif %}" href="#" id="navbarPoemsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="Home">
									Home
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarPoemsDropdown">
									<a class="dropdown-item {{ request|active_link_class:'/poems/eft_offers.html' }}" href="{% url 'poems:eft_offers' %}" title="EFT Offers">EFT Offers</a>
									<a class="dropdown-item {{ request|active_link_class:'/poems/eft_purchases.html' }}" href="{% url 'poems:eft_purchases' %}" title="EFT Purchases">EFT Purchases</a>
								</div>
							</li>
	{% endif %}
	{% if request.user.is_authenticated %}
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle {{ request|active_link_class_profile }} {% if request|active_link_class:'/password-change/' or request|active_link_class:'/password-change-done/' or request|active_link_class:'/password-reset/' or request|active_link_class:'/password-reset-done/' or  request|active_link_class:'/logout.html' or request|active_link_class:'/members/edit.html' %}active{% endif %}" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<i class="fa fa-id-card" aria-hidden="true"></i>
 Membership
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropdown">
									<a class="dropdown-item {{ request|active_link_class_profile }}" href="{{ request.user|author_url }}" data-request-path="{{ request.path }}" title="Poet Member Profile">Profile</a>
		{% if request.user.is_staff %}
									<a class="dropdown-item" href="{% url 'admin:index' %}" title="Staff Interface"><i class="fas fa-users-cog"></i> Staff</a>
		{% endif %}
									<a class="dropdown-item {% if request|active_link_class:'/members/edit.html' %}active{% endif %}" href="{% url 'members:edit' %}" title="Settings">Settings</a>
									<a class="dropdown-item {% if request|active_link_class:'/password-change/' or request|active_link_class:'/password-change-done/' %}active{% endif %}" href="{% url 'password_change' %}" title="Member Change Password">Change Password</a>

									<div class="dropdown-divider"></div>
									<a class="dropdown-item {{ request|active_link_class:'/logout.html' }}" href="{% url 'logout' %}" title="Member Logout"><i class="fas fa-sign-out-alt"></i> Logout</a>
								</div>
							</li>
							<li class="nav-item">
								<a class="nav-link {{ request|active_link_class:'/members/welcome.html' }}" href="{% url 'members:welcome' %}" title="Welcome to Here by inLoveLike"><i class="fas fa-info"></i> Welcome</a>
							</li>
	{% else %}
							<li class="nav-item">
								<a class="nav-link {{ request|active_link_class:'/login.html' }}" href="{% url 'login' %}" title="Poet Login"><i class="fas fa-sign-in-alt"></i> Login</a>
							</li>
							<li class="nav-item">
								<a class="nav-link {{ request|active_link_class:'/register-basic.html' }}" href="{% url 'register_eft' %}" title="Membership is Free"><i class="fas fa-user"></i> Membership</a>
							</li>
	{% endif %}
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownSocial" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<i class="fas fa-icons"></i> Social
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropdownSocial">
									<a class="dropdown-item" href="https://www.facebook.com/inlovelike/" title="inLoveLike on Facebook"><i class="fa fa-facebook"></i> Facebook @inlovelike</a>
									<a class="dropdown-item" href="https://www.instagram.com/inlovelike_/" title="inLoveLike on Instagram"><i class="fa fa-instagram"></i> Instagram @inlovelike_</a>
									<a class="dropdown-item" href="https://twitter.com/inlovelike_" title="inLoveLike on Twitter"><i class="fa fa-twitter"></i> Twitter @inlovelike_</a>
									<a class="dropdown-item" href="https://inlovelikecom.tumblr.com/" title="inLoveLike on Tumblr"><i class="fa fa-tumblr"></i> Tumblr @inlovelikecom</a>
								</div>
							</li>
	
						</ul>
						<form method="get" action="{% url 'poem_search_get' %}" class="form-inline my-2 my-lg-0">
							<input class="form-control mr-sm-2" name="q" value="{% if request|q_request_get %}{{ request|q_request_get }}{% else %}{{ request|search_q_value }}{% endif %}" type="search" placeholder="Search" aria-label="Search">
							<button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search btn btn-sm text-dark"></i></button>
							<a href="{% url 'search_advanced' %}?q={% if request|q_request_get %}{{ request|q_request_get }}{% else %}{{ request|search_q_value }}{% endif %}" class="btn btn-lg"><i class="fas fa-cogs"></i></a>
						</form>
					</div>
				</nav>
{% block content %}
{% endblock %}
			</div>
		</main>
		<footer class="mt-4">

			<p>&copy; <a href="http://nshbrown.com/?inlovelike">Nathaniel Steven Henry Brown</a> and respective <a href="{% url 'members:list' %}" title="Member Statistics for inLoveLike">Authors</a>. All Rights Reserved.</p>

			{% if request.user|member_tips_is:'verbose' %}
			<div class="alert alert-info" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h6 class="alert-heading text-left">Sitemap and RSS for Seach engines and content aggregators</h6>
				<p class="text-left">We have structured our sitemap to conform with the likes of Google and Microsoft's Bing. In addition we have also created a RSS2 feed that highlights changes done to the website.</p>
			</div>
			{% endif %}

			<p><a href="{{request|host}}sitemap.xml" title="Sitemap for inLoveLike" class="btn btn-info btn-sm sitemap"><i class="fa fa-sitemap" aria-hidden="true"></i> Sitemap</a><a href="{{request|host}}rss2.xml" title="RSS 2.0 for inLoveLike" class="btn btn-info btn-sm rss2 ml-2"><i class="fas fa-rss"></i> RSS</a></p>

			{% if request.user|member_tips_is:'verbose' %}
			<div class="alert alert-info" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h6 class="alert-heading text-left">Customize your home screen</h6>
				<p class="text-left">Simply change the <a href="{% url 'members:edit' %}" title="Settings">setting</a> for your profile and you will get a new destination when you click on any of the logos.</p>
			</div>
			{% endif %}

			<p class="logo"><a href="{{ request.user|home_screen_url }}"><img src="{% static 'thumbnail-v2_0-202103271109.png' %}" height="40" alt="inLoveLike" /> <span>inLoveLike</span></a></p>
			<p>Powered by the <a href="https://inlovelike.com/pricing.html" title="EFT Here Server by inLoveLike" rel="external">EFT Here Server</a>. An <a href="https://inlovelike.com" title="inLoveLike - Poetry with Poems" rel="external">inLoveLike</a> production.</p>
		</footer>
	</body>
</html>
{% comment %}
Sources:
https://stackoverflow.com/questions/719915/how-to-put-comments-in-django-templates
https://getbootstrap.com/docs/3.4/css/
https://popper.js.org/
https://www.w3schools.com/tags/att_form_method.asp
https://getbootstrap.com/docs/4.0/components/navbar/
https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons
https://stackoverflow.com/questions/19827605/change-bootstrap-navbar-collapse-breakpoint-without-using-less
{% endcomment %}