here/here/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

# https://docs.djangoproject.com/en/3.1/ref/urls/#handler403
from django.conf.urls import handler400, handler403, handler404, handler500
from pages import views as page_views
from members import views as member_views
from poems import views as poem_views

urlpatterns = [
    path("", page_views.index, name="index"),
    path('sitemap.xml', page_views.sitemap, name="sitemap"),
    path('sitemaps.xml', page_views.sitemap),
    path('admin/', admin.site.urls),
    re_path(r'^profile-.*-(?P<user_id>\d+)\.html$', member_views.profile, name="member_profile"),
    re_path(r'^profile-(?P<user_id>\d+)\.html$', member_views.profile, name="member_profile_id"),
   	path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
    path('login.html',auth_views.LoginView.as_view(template_name='members/login.html'), name='login'),
    path('logout.html', auth_views.LogoutView.as_view(template_name="members/logged_out.html"), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name="accounts/password_change_form.html"), name="password_change"),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"), name="password_change_done"),
    path('members/', include('members.urls')),
    # path('search.html', poem_views.search_get, name="poem_search_get"),
    path('rss2.xml', page_views.rss2, name="rss2"),
    path('robots.txt', page_views.robots, name="robots"),
    # path('search_advanced.html', poem_views.search_advanced, name="search_advanced"),
    path("register-eft.html", member_views.register_eft, name="register_eft"),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset_form.html", from_email=settings.EMAIL_FROM), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"), name='password_reset_done'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), name='password_reset_complete'),
    re_path(r'^eft-(?P<sha512>\w+)\.json$', poem_views.eft_get, name="root_eft"),
    path('poems/', include('poems.urls')),
    path('search.html', poem_views.search_get, name="poem_search_get"),
    path('search_advanced.html', poem_views.search_advanced, name="search_advanced"),
]

handler400 = page_views.catch_redirect
handler403 = page_views.catch_redirect
handler404 = page_views.catch_redirect
handler500 = page_views.catch_redirect


# Sources:
# https://docs.djangoproject.com/en/3.1/topics/auth/default/

here/poems/urls.py
# from django.urls import include, path, re_path

from . import views
from django.urls import path, re_path


app_name = 'poems'
urlpatterns = [
    path('eft_offers.html', views.eft_offers, name='eft_offers'),
    path('eft_purchases.html', views.eft_purchases, name='eft_purchases'),
    path('eft-purchase-gallery/<int:eft_purchase_id>/', views.eft_purchase_gallery, name='eft_purchase_gallery'),
    path('eft-purchase-remove/<int:eft_purchase_id>/', views.eft_purchase_remove, name='eft_purchase_remove'),
    path('eft-purchase-offer/<uuid:eft_purchase_guid>/', views.eft_purchase_offer, name='eft_purchase_offer'),
    re_path(r'^eft-purchase-offer-sold/(?P<guid>.*)/$', views.eft_purchase_offer_sold, name="eft_purchase_offer_sold"),
    re_path(r'^eft-purchase-offer-refund/(?P<guid>.*)/$', views.eft_purchase_offer_refund, name="eft_purchase_offer_refund"),
    path('eft-purchase-resell/<int:eft_purchase_id>/', views.eft_purchase_resell, name='eft_purchase_resell'),
    path('eft_purchase_upload_ajax', views.eft_purchase_upload_ajax, name='eft_purchase_upload_ajax'),
    re_path(r'^eft-transfer-get/(?P<sha512>.*).json$', views.eft_transfer_get, name="eft_transfer_get"),
]

here/poems/forms.py
from django import forms
from django.forms import ModelForm
# from django.core.exceptions import ValidationError
# from django.contrib.auth.models import User
# from django.utils.translation import gettext_lazy as _
# from captcha.fields import ReCaptchaField
from django.utils.html import strip_tags
from django.conf import settings
from decimal import *

class EftPurchaseUploadAjaxForm(forms.Form):
	source = forms.ChoiceField(label="Source URL", widget=forms.Select(attrs={'class': 'form-control'}), choices=settings.EFT_PURCHASE_SOURCES_CHOICES)

	sha512 = forms.CharField(label='SHA 512', widget=forms.TextInput(attrs={'class': 'form-control'}))

	key = forms.CharField(required=False, label='Transfer Key (Optional)', widget=forms.TextInput(attrs={'class': 'form-control'}))

	fields = ['source', 'sha512', 'key']

class EftPurchaseUploadCompleteAjaxForm(forms.Form):
	source = forms.ChoiceField(label="Source URL", widget=forms.Select(attrs={'class': 'form-control'}), choices=settings.EFT_PURCHASE_SOURCES_CHOICES)
	sha512 = forms.CharField(label='SHA2-512 ir SHA3-512', widget=forms.TextInput(attrs={'class': 'form-control'}))
	drm = forms.CharField(
		required=True,
		label='DRM',
		initial='', 
		widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
	)
	version = forms.CharField(label='Version', widget=forms.TextInput(attrs={'class': 'form-control'}))
	cost = forms.DecimalField(required=False, label='Cost', widget=forms.TextInput(attrs={'placeholder': "0.00", 'class': 'form-control'}))

	fields = ['source', 'sha512', 'drm', 'version', 'cost']

class EftPurchaseOfferForm(forms.Form):
	price = forms.DecimalField(min_value=Decimal(0.0), label='EFT Price you want to pay', widget=forms.TextInput(attrs={'placeholder': "0.00", 'class': 'form-control'}))
	name = forms.CharField(label='Your Name', widget=forms.TextInput(attrs={'class': 'form-control'}))
	email = forms.EmailField(label='Your Email', widget=forms.TextInput(attrs={'class': 'form-control'}))
	comment = forms.CharField(
		required=False,
		label='Any comments?',
		initial='', 
		widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
	)

	if settings.FEATURE_CAPTCHA:
		captcha = ReCaptchaField()

	fields = ['price', 'name', 'email', 'comment']


# Sources: 
# https://docs.djangoproject.com/en/3.1/topics/forms/modelforms/
# https://docs.djangoproject.com/en/3.1/ref/forms/api/
# https://docs.djangoproject.com/en/3.1/ref/forms/fields/
# https://docs.djangoproject.com/en/3.1/ref/models/fields/
# https://docs.djangoproject.com/en/3.1/ref/forms/validation/
# https://stackoverflow.com/questions/48030567/how-to-customize-username-validation
# https://stackoverflow.com/questions/9324432/how-to-create-password-input-field-in-django
# https://stackoverflow.com/questions/11443658/how-do-i-add-a-class-to-a-choicefield-in-django/11443704
# https://stackoverflow.com/questions/6862250/change-a-django-form-field-to-a-hidden-field
# https://docs.djangoproject.com/en/3.2/ref/forms/fields/

here/poems/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import redirect
from django.utils import timezone
from django.db.models import Q, OuterRef
from django.core.serializers.json import DjangoJSONEncoder

from poems.models import EftPurchase, EftPurchaseOffer, EftResell, DivideMe
from poems.forms import EftPurchaseUploadAjaxForm, EftPurchaseUploadCompleteAjaxForm, EftPurchaseOfferForm
from members.templatetags import member_tag_extras
from members.models import Member
import logging
import re
import functools
import operator
import hashlib
import json
from decimal import *

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create your views here.

@csrf_exempt
def eft_get(request, sha512):
	eft = False
	json_data = {
		'error': True,
		'message': 'Default',
	}

	divide_me = DivideMe()
	source_contract_address = divide_me.get_contract_address_for_host(settings.HTTPS_BASE_URL)

	try:
		eft_resell = EftResell.objects.get(sha512=sha512)
	except EftResell.DoesNotExist:
		eft_resell = False
		json_data['message'] = 'EFT Does not exist'
	except Exception as e:
		json_data = { 'success': False, 'message': 'Exception occurred. ' + str(e)}
		eft_resell = False

	if eft_resell:
		json_data = {
			'cost': eft_resell.cost,
			'drm': eft_resell.drm,
			'sha512': eft_resell.sha512,
			'sha3_512': eft_resell.sha3_512,
			'version': settings.EFT_CURRENT_VERSION,
			'source': settings.HTTPS_BASE_URL,
		}
		json_data['member_contract_address'] = eft_resell.eft_purchase.member().contract_address

	json_data['source_contract_address'] = source_contract_address

	response = JsonResponse(json_data)
	return response

@login_required
def eft_offers(request):
	member = request.user.member_user.first()

	eft_purchases = EftPurchase.objects.filter(owner=request.user).values_list('id', flat=True)
	resell_offers = EftPurchaseOffer.objects.filter(eft_purchase__in=list(eft_purchases)).order_by('created').reverse()

	resell_offers

	options = {
		'resell_offers': resell_offers,
		'success': request.GET.get('success', False),
		'error': request.GET.get('error', False),
		'seo_title': 'EFT Requests with inLoveLike'
	}
	return render(request, 'poems/eft_offers.html', options)


@login_required
def eft_purchases(request):
	user = request.user
	member = user.member_user.first()

	if member.standing == settings.MEMBER_STANDING_CANCELLED:
		response = redirect('/members/intro.html?error=cancelled')
		return response

	eft_purchases = EftPurchase.objects.filter(owner=user).reverse()

	form_eft_ajax = EftPurchaseUploadAjaxForm()

	options = {
		'eft_purchases': eft_purchases,
		# 'form': form,
		'form_eft_ajax': form_eft_ajax,
		'success': request.GET.get('success', False),
		'error': request.GET.get('error', False),
		'message': request.GET.get('message', False),
	}
	return render(request, 'poems/eft_purchases.html', options)


@login_required
def eft_purchase_upload_ajax(request):
	user = request.user
	member = user.member_user.first()

	json_data = { 'success': False }

	if member.standing != settings.MEMBER_STANDING_CANCELLED:
		if request.method == 'POST':
			valid = False

			form = EftPurchaseUploadCompleteAjaxForm(request.POST or None)
			if form.is_valid():
				# Verify valid data from the url
				# {{ source }}poems/eft-verify/{{ sha512 }}.json
				sha512 = form.cleaned_data["sha512"]
				source = form.cleaned_data["source"]
				drm = form.cleaned_data["drm"]
				version = form.cleaned_data["version"]
				cost = form.cleaned_data["cost"]

				print("eft_purchase_load_ajax-> success is True")

				# If valid, get the base64 and version
				# {{ source }}poems/eft-get/{{ sha512 }}.json

				eft_file_data = {
					'sha512': sha512,
					'source': source,
					'version': version,
					'drm': drm,
					'cost': cost,
				}

				eft_file_str = json.dumps(eft_file_data, cls=DjangoJSONEncoder, default = str)

				try:
					eft_purchase = EftPurchase()
					eft_purchase.eft_file = eft_file_str
					eft_purchase.owner = request.user
					eft_purchase.save()
					json_data = { 'success': True }
				except Exception as e:
					json_data = { 'success': False, 'message': 'An exception has occurred: ' + str(e) }
					if form.errors:
						json_data['message'] = json_data['message'] + form.errors.join(", ")
			else:
				json_data = { 'success': False, 'message': 'Form is not valid', 'form': form.errors }

	response = JsonResponse(json_data)
	return response

@login_required
def eft_purchase_gallery(request, eft_purchase_id):
	eft_purchase = get_object_or_404(EftPurchase, pk=eft_purchase_id)

	member = request.user.member_user.first()
	if eft_purchase.owner != request.user and request.user.is_staff is False:
		response = redirect('/poems/eft_purchases.html?error=eft_purchase_gallery')
		return response

	if eft_purchase.visible is True:
		eft_purchase.visible = False
	else:
		eft_purchase.visible = True

	eft_purchase.save()

	response = redirect('/poems/eft_purchases.html?success=eft_purchase_gallery')
	return response


@login_required
def eft_purchase_remove(request, eft_purchase_id):
	eft_purchase = get_object_or_404(EftPurchase, pk=eft_purchase_id)

	member = request.user.member_user.first()
	if eft_purchase.owner != request.user and request.user.is_staff is False:
		response = redirect('/poems/eft_purchases.html?error=eft_purchase_remove')
		return response

	if request.user.is_staff is False:
		response = redirect('/poems/eft_purchases.html?error=not_admin')
		return response

	eft_purchase.delete()

	response = redirect('/poems/eft_purchases.html?success=eft_purchase_remove')
	return response


def eft_purchase_offer(request, eft_purchase_guid):
	eft_purchase = get_object_or_404(EftPurchase, guid=eft_purchase_guid)

	request.session['referral'] = request.META.get('HTTP_REFERER', request.session.get('referral', ''))

	eft_resell = eft_purchase.file()

	if request.user.is_authenticated:
		price = request.POST.get('price', eft_resell.cost)
		name = request.POST.get('name', member_tag_extras.author_title(request.user))
		email = request.POST.get('email', request.user.email)
		comment = request.POST.get('comment', '')
	else:
		price = request.POST.get('price', eft_resell.cost)
		name = request.POST.get('name', '')
		email = request.POST.get('email', '')
		comment = request.POST.get('comment', '')

	eft_purchase_offer_form_data = {
		'price': price,
		'name' : name,
		'email' : email,
		'comment' : comment,
	}

	if request.method == 'POST':
		# I Wish I could have more than one Form on the POST so variables don't conflict
		# request.POST['Poem'].get('title', 'Empty')
		# request.POST['Member'].get('pricing', settings.MEMBER_PRICING_FREE)
		form = EftPurchaseOfferForm(eft_purchase_offer_form_data)
		if form.is_valid():
			try:
				if form.cleaned_data['price']:
					price = form.cleaned_data['price']
				else:
					price = Decimal(0)
					
				epo = EftPurchaseOffer.objects.create(
					price=price,
					name=form.cleaned_data['name'],
					email=form.cleaned_data['email'],
					comment=form.cleaned_data['comment'],
					eft_purchase=eft_purchase,
				)
				response = redirect('/poems/eft-purchase-offer/' + str(eft_purchase.guid) + '/?success=created&po=' + str(epo.price))
				return response
			except Exception as e:
				logger.info("eft_purchase_offer -> Exception")
				logger.info(e)
				response = redirect('/poems/eft-purchase-offer/' + str(eft_purchase.guid) + '/?error=created&e=' + str(e))
				return response

	else:
		form = EftPurchaseOfferForm(eft_purchase_offer_form_data)

	options = {
		'seo_title': 'Purchase a poem as an EFT with inLoveLike',
		'eft_purchase': eft_purchase,
		'form': form,
		'eft_resell': eft_resell,
		'success': request.GET.get('success', False),
		'error': request.GET.get('error', False),
	}
	return render(request, 'poems/eft_purchase_offer.html', options)

@login_required
def eft_purchase_offer_sold(request, guid):
	eft_purchase_offer = get_object_or_404(EftPurchaseOffer, pk=guid)

	member = request.user.member_user.first()
	if eft_purchase_offer.eft_purchase.owner != request.user and request.user.is_staff is False:
		response = redirect('/poems/eft_offers.html?error=resold_not_owner')
		return response

	if eft_purchase_offer.sold is False:

		# subject, from_email, to = 'hello', 'nate@purefame.com', 'nate@purefame.com'
		# text_content = 'This is an important message.'
		# html_content = '<p>This is an <strong>important</strong> message.</p>'
		# msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
		# msg.attach_alternative(html_content, "text/html")
		# msg.send()

		now = timezone.now()
		eft_purchase_offer.sold = True
		eft_purchase_offer.sold_on = now
		eft_purchase_offer.key = hashlib.sha512(str(timezone.now()).encode('utf-8')).hexdigest()
		eft_purchase_offer.save()

		# subject = 'You have acquired an Electronic File Token (EFT) with inLoveLike'
		# html_message = render_to_string('poems/eft_sold_email.html', {'eft': eft})
		# plain_message = strip_tags(html_message)
		# from_email = 'inLoveLike <' + settings.EMAIL_FROM + '>'
		# to = eft.email

		# mail.send_mail(subject, plain_message, from_email, [to], html_message=html_message)
		# mail.send_mail('Subject here', 'Here is the message.', 'nate@purefame.com', ['nate@purefame.com'], fail_silently=False)
		response = redirect('/poems/eft_offers.html?success=resold')
		return response
	else:
		response = redirect('/poems/eft_offers.html?error=resold')
		return response


@login_required
def eft_purchase_offer_refund(request, guid):
	eft_purchase_offer = get_object_or_404(EftPurchaseOffer, pk=guid)

	member = request.user.member_user.first()
	if eft_purchase_offer.eft_purchase.owner != request.user and request.user.is_staff is False:
		response = redirect('/poems/eft_offers.html?error=refund_not_owner')
		return response

here/poems/templates/poems/_eft_purchase_edit.html
{% load poem_tag_extras %}
{% load member_tag_extras %}
{% if request.user.is_staff and eft_purchase.owner != request.user %}
<a href="/admin/poems/eft_purchase/{{ eft_purchase.id }}/change/" {% if eft_purchase|eft_purchase_is_resold %}class="text-warning"{% endif %}><i class="fas fa-pen"></i></a> 
{% elif eft_purchase.owner == request.user %}
<a href="/poems/eft_purchases.html" {% if eft_purchase|eft_purchase_is_resold %}class="text-warning"{% endif %}><i class="fas fa-pen"></i></a>
{% endif %}

here/poems/templates/poems/_eft_purchase_poem_body.html
{% load poem_tag_extras %}
{% load member_tag_extras %}

{% if eft_purchase.poem_title|poem_is_file %}
	{% if eft_purchase.file_cache|poem_file_cache_is_image %}

<div class="card-body"><img src="/media/{{ eft_purchase.file_cache }}" class="mw-100" /></div>

	{% elif eft_purchase.file_cache|poem_file_cache_is_audio %}

<div class="card-body"><audio controls class="mw-100">
	<source src="/media/{{ eft_purchase.file_cache }}" type="audio/mp4" />
	<p>Your browser does not support HTML5 audio.</p>
 </audio></div>
	 {% elif eft_purchase.file_cache|poem_file_cache_is_video %}
<div class="card-body"><video controls class="mw-100">
	<source src="/media/{{ eft_purchase.file_cache }}">
	<p>Your browser does not support the video element. Kindly update it to latest version.</p>
</video></div>
	{% endif %}
	{% if show_file %}
<div class="card-body">File Location: <a href="/media/{{ eft_purchase.file_cache }}">/media/{{ eft_purchase.file_cache }}</a></div>
	{% endif %}
{% else %}

	{% if eft_purchase.poem_title|poem_is_code_full %}
<pre class="text-left">{{ eft_purchase.poem_body|escape|poem_as_display_code_full|safe }}</pre>
	{% elif eft_purchase.poem_title|poem_is_code %}
<pre class="text-left">{{ eft_purchase.poem_body|escape|poem_as_display_code|safe }}</pre>
	{% else %}
<div class="card-text">{{ eft_purchase.poem_body|linebreaks|safe }}</div>
	{% endif %}

{% endif %}	
{% comment %}
Sources:
https://wpbeaches.com/html-5-set-up-audio-across-all-browsers-using-m4a-oga-mp3/
{% endcomment %}

here/poems/templates/poems/eft_purchases.html
{% extends 'theme.html' %}
{% load static %}
{% load page_tag_extras %}
{% load poem_tag_extras %}
{% load member_tag_extras %}
{% block content %}
<div class="poems-commissions">
<h4 class="text-info mb-4">EFT Purchases</h4>
	{% if success %}
<div class="alert alert-success" role="alert">
		{% if success == 'import' %}
	Thank you, your EFT purchase has been imported.{% if message %} "{{ message }}".{% endif %} 
		{% else %}
	That was a success.{% if message %} "{{ message }}".{% endif %} 
		{% endif %}
</div>
	{% endif %}
	{% if error %}
<div class="alert alert-warning" role="alert">
		{% if error == 'import' %}
	There has been an error while importing a EFT purchase.{% if message %} "{{ message }}".{% endif %}
		{% elif error == 'unauthorized' %}
	You are not authorized to touch that EFT purchase.{% if message %} "{{ message }}".{% endif %}
		{% else %}
	There was an error.{% if message %} "{{ message }}".{% endif %} Please try again!
		{% endif %}
</div>
	{% endif %}
	{% if eft_purchases %}
<p>All your EFT purchases on inLoveLike.</p>
{% if request.user|member_tips_is:'some' or request.user|member_tips_is:'verbose' %}
<div class="alert alert-info alert-dismissible fade show" role="alert">
	Here you will find all the <strong>EFT Purchases</strong> in your account. When you add an EFT through the use of the form at the bottom of this page, you will see your Profile includes the EFT by default. Simply click the button to hide it from your profile if you so design. Verifying an EFT links to a potential remote server that has been approved. If you see True for success, then it's valid. 
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
	<span aria-hidden="true">&times;</span>
	</button>
</div>
{% endif %}
<div class="list-group eft_purchases">
	{% for eft_purchase in eft_purchases %}
	<div class="eft_purchase list-group-item list-group-item-action mb-2">
		{% if eft_purchase.valid %}
        <div class="d-flex w-100 justify-content-between">
	        <h5 class="mb-1 title"><a href="{% url 'poems:eft_purchases' %}" class="btn btn-lg btn-info">{{ eft_purchase.poem_guid }}</a></h5>
	        <div>
		        <small>{{ eft_purchase.version }}</small><br />
		        <small>Purchased on: {{ eft_purchase.eft_purchased_on|date:'F d, Y'  }}</small><br />
		        <small>Imported on {{ eft_purchase.imported_on|date:'F d, Y' }}</small>
	    	</div>
	    </div>
        <p class="mb-1">
        	Source: {{ eft_purchase.source }}<br />
			{% if not eft_purchase.poem_title|poem_is_free %}
	        	Cost: <span class="btn btn-sm btn-dark text-warning">{{ eft_purchase.cost|cost_as_display|safe }}</span>
	        	{% if eft_purchase.price %}<br>
	        	Bid: <span class="btn btn-sm btn-dark text-warning">P{{ eft_purchase.price|cost_as_display}}</span>
	        	{% endif %}
	        	Selling: <span class="btn btn-sm btn-dark text-warning">{{ eft_purchase|eft_purchase_resell_cost|safe }}</span>
	        {% else %}
	        	Cost: <span class="btn btn-sm btn-dark text-warning">{{ 0|cost_as_display|safe }}</span>	        
	        {% endif %}
        </p>	
        <p><small><span class="font-weight-bold">EFT SHA612:</span> {{ eft_purchase.sha512 }}</small></p>
        <small><span class="font-weight-bold">Poem Title:</span> {{ eft_purchase.poem_title }}</small>
        <div><small><span class="font-weight-bold">Poem Body:</span></small></div>

	    {% include 'poems/_eft_purchase_poem_body.html' with show_file=True %}	
    	
	        {% if eft_purchase.visible %}
        <a href="/poems/eft-purchase-gallery/{{ eft_purchase.id }}/" class="btn btn-sm btn-warning mt-3">Remove from Profile</a>
        <a href="{{ request.user|author_url }}#eft-{{ eft_purchase.guid }}" class="btn btn-sm btn-info mt-3">View in  Profile</a>
	        {% else %}
        <a href="/poems/eft-purchase-gallery/{{ eft_purchase.id }}/" class="btn btn-sm btn-success mt-3">Add to Profile's EFT Gallery</a>
			{% endif %}
			{% if not eft_purchase.poem_title|poem_is_free %}
	        	{% if eft_purchase.resell_exclusion %}
	        <a href="/poems/eft-purchase-resell/{{ eft_purchase.id }}/" class="btn btn-sm btn-success mt-3">Resell EFT</a>
				{% else %}
	        <a href="/poems/eft-purchase-resell/{{ eft_purchase.id }}/" class="btn btn-sm btn-warning mt-3">Don't Resell EFT</a>
			    {% endif %}
			{% endif %}
        
        <a href="{{ eft_purchase.source }}poems/eft-verify/{{ eft_purchase.sha512 }}.json" class="btn btn-sm btn-success ml-3 mt-3 float-right">Verify EFT</a>
		{% else %}
        <h5 class="mb-1 title">Invalid EFT Purchase {% if eft_purchase.poem_guid %}<small>{{ eft_purchase.poem_guid }}</small>{% endif %}</h5> 
       	{% endif %}		
       	{% if request.user.is_staff %}
        <a href="/poems/eft-purchase-remove/{{ eft_purchase.id }}/" class="btn btn-sm btn-danger ml-3 mt-3 float-right">Remove EFT Purchase</a>
        {% endif %}

	</div>
	{% endfor %}
</div>

	{% else %}
<p class="text-info">You currently have no EFT purchases with inLoveLike.</p>
	{% endif %}



	<div class="card h-100 my-1 mx-3 my-3">				
	    <div class="card-body">
			<div class="alert alert-success alert-dismissible fade show" role="alert">
				<p>Importing an <strong>EFT Purchase</strong> is quite simple. Simply choose either the Development or alternative server and enter in the SHA512 Electronic File Token and click Fetch EFT. Once completed, the page will refresh with a message. You can acquire SHA512 EFT's by completing the process behind bidding on them through the access of the Poem</p>
				<ul>
					<li>V2 means it has been verified twice. Once in the browser and another within the code</li>
					<li>V1W1 means it has been verified once within the browser and is on the whitelist within the code.</li>  

				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<h4 class="card-title">Import EFT Purchase</h4>
			<form class="eft-purchase-upload-ajax" action="{% url 'poems:eft_purchase_upload_ajax' %}" method="post">
				<div class="d-none data-destination" data-destination="{{ request|host }}"></div>
			    {% csrf_token %}
			    {{ form_eft_ajax }}
				<button type="submit" class="btn btn-primary mt-2" data-loading="true">Fetch EFT</button>
			</form>
		</div>
	</div>

</div>
{% endblock %}
{% comment %}
Sources:
https://getbootstrap.com/docs/4.0/components/alerts/
{% endcomment %}

here/poems/templates/poems/search.html
{% extends 'theme.html' %}
{% load static %}
{% load poem_tag_extras %}
{% load member_tag_extras %}
{% block content %}
    <div class="poems-search">
	{% if eft_purchase_matches|length > 0 %}
		<h4 class="text-secondary">All Poems Matching "{{ term }}"</h4>
		<ul class="list-group">
	    {% for eft_purchase in eft_purchase_matches %}
    		<li class="list-group-item d-flex justify-content-between mb-2">
                {% include 'poems/_search_eft_purchase_item.html' %}
    		</li>
	    {% endfor %}
    	</ul>
    {% else %}
  		<h4 class="text-warning">There are no Poems Matching "{{ term }}".</h4>
  		<p class="text-info">Sorry, there are no poems that match that phrase.</p>
    {% endif %}
    </div>
{% endblock %}